// Task
export const SAVE_TASK = "SAVE_TASK";
export const SHOW_ALL_TASK = "SHOW_ALL_TASK";
export const SHOW_SELECTED_TYPE = "SHOW_SELECTED_TYPE";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE TASK";

// Durian
export const ADD_DURIAN = "ADD_DURIAN";
export const SHOW_ALL_DURIAN = "SHOW_ALL_DURIAN";
export const UPDATE_DURIAN = "UPDATE_DURIAN";
export const DELETE_DURIAN = "DELETE_DURIAN";

// Visualization
export const SHOW_WATER_CHART = "SHOW_WATER_CHART";
export const ADD_ACCOUNT_BOOK = "ADD_ACCOUNT_BOOK";
export const SHOW_SUM_INCOME_OUTCOME = "SHOW_SUM_INCOME_OUTCOME";
export const SHOW_ACCOUNT_BOOK = "SHOW_ACCOUNT_BOOK";
export const UPDATE_ACCOUNT_BOOK = "UPDATE_ACCOUNT_BOOK";
export const DELETE_ACCOUNT_BOOK = "DELETE_ACCOUNT_BOOK";

export const SHOW_RECORD_DISEASE = "SHOW_RECORD_DISEASE";
export const DELETE_RECORD_DISEASE = "DELETE_RECORD_DISEASE";

// Appointment
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const SHOW_APPOINTMENT = "SHOW_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const FIND_APPOINTMENT_BY_PRIORITY = "FIND_APPOINTMENT_BY_PRIORITY";

// User

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const SET_USERNAME_NAVBAR = "SET_USERNAME_NAVBAR";

